---
title: Poole
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
relative_permalinks: true
tagline: The Jekyll Butler
url: http://getpoole.com
paginate: 1
baseurl: ''
sass:
  sass_dir: _sass
  style: :compressed
author:
  name: Mark Otto
  url: https://twitter.com/mdo
  email: markdotto@gmail.com
version: 1.0.0
github:
  repo: https://github.com/poole/poole
